<template>
    <div class="bg-[#F3F6F9] px-5 md:px-[30px] lg:px-0">
        <div class="container max-w-7xl mx-auto py-7 md:py-[60px]">
            <div class="flex flex-col gap-5">
                <h2 class="font-outfit text-[#00274D] text-3xl md:text-4xl lg:text-5xl md:leading-[46px] font-semibold uppercase leading-tight" style="color: #00274D;">
                    Privacy Policy
                </h2>
                <div class="flex items-center text-[#0f75bc] text-[16px]">
                    <!-- <span> -->
                        <svg aria-hidden="true" class="mr-1" fill="#0f75bc" width="16" height="16" viewBox="0 0 448 512"><path d="M148 288h-40c-6.6 0-12-5.4-12-12v-40c0-6.6 5.4-12 12-12h40c6.6 0 12 5.4 12 12v40c0 6.6-5.4 12-12 12zm108-12v-40c0-6.6-5.4-12-12-12h-40c-6.6 0-12 5.4-12 12v40c0 6.6 5.4 12 12 12h40c6.6 0 12-5.4 12-12zm96 0v-40c0-6.6-5.4-12-12-12h-40c-6.6 0-12 5.4-12 12v40c0 6.6 5.4 12 12 12h40c6.6 0 12-5.4 12-12zm-96 96v-40c0-6.6-5.4-12-12-12h-40c-6.6 0-12 5.4-12 12v40c0 6.6 5.4 12 12 12h40c6.6 0 12-5.4 12-12zm-96 0v-40c0-6.6-5.4-12-12-12h-40c-6.6 0-12 5.4-12 12v40c0 6.6 5.4 12 12 12h40c6.6 0 12-5.4 12-12zm192 0v-40c0-6.6-5.4-12-12-12h-40c-6.6 0-12 5.4-12 12v40c0 6.6 5.4 12 12 12h40c6.6 0 12-5.4 12-12zm96-260v352c0 26.5-21.5 48-48 48H48c-26.5 0-48-21.5-48-48V112c0-26.5 21.5-48 48-48h48V12c0-6.6 5.4-12 12-12h40c6.6 0 12 5.4 12 12v52h128V12c0-6.6 5.4-12 12-12h40c6.6 0 12 5.4 12 12v52h48c26.5 0 48 21.5 48 48zm-48 346V160H48v298c0 3.3 2.7 6 6 6h340c3.3 0 6-2.7 6-6z"></path></svg>
                    <!-- </span> -->
                    <span>
                        Effective as of December 2, 2025
                    </span>
                </div>
                <hr>
                <p class="text-[16px] text-gray-700">Legacy Solutions LLC is a Louisiana limited liability company. This Privacy Policy sets forth the policies and practices governing the collection, use, maintenance, safeguarding, and disclosure of information submitted or made available by individuals who choose to visit or interact with this landing page or who choose to communicate with Legacy Solutions LLC through any related channel of communication. The purpose of this Privacy Policy is to provide a clear description of our information practices, consistent with the obligations imposed under applicable state and federal law, and to ensure that users of this landing page understand the manner in which their information may be handled.</p>
                <p class="text-[16px] text-gray-700">Legacy Solutions LLC does not obtain personal information except where it is voluntarily provided by an individual or where it is collected through customary, automated means associated with ordinary operation of a web page. When a visitor submits information through a form, email, text message, or telephone call, the information provided may include the person’s name, email address, telephone number, mobile number, residential or mailing address, and any factual details relating to the subject of their inquiry. This information is accepted as submitted and is used exclusively for the business purposes of Legacy Solutions LLC. Legacy Solutions LLC does not solicit information of a sensitive nature, such as Social Security numbers, driver’s license numbers, financial account numbers, or similar identifiers, and visitors should not provide such information unless expressly requested for a lawful and legitimate purpose.</p>
                <p class="text-[16px] text-gray-700">As part of the regular operation of this landing page, Legacy Solutions LLC may receive limited technical information generated automatically when the page is accessed. This may include an Internet Protocol address, general location information inferred from the IP address, device information, browser information, timestamps, session identifiers, and similar data related to the functionality and security of the page. This information is used solely in connection with system performance, website administration, prevention of misuse, and maintenance of security measures understood to be reasonably necessary for digital operations.</p>
                <p class="text-[16px] text-gray-700">The personal information voluntarily submitted is used to respond to inquiries, to contact individuals regarding matters related to services offered by Legacy Solutions LLC, to verify identity where appropriate, and to maintain internal records consistent with good business practice. The information may also be used to comply with legal obligations, including obligations arising under Louisiana law, federal law, court orders, subpoenas, administrative directives, or other lawful processes.</p>
                <p class="text-[16px] text-gray-700">If a mobile number is provided, Legacy Solutions LLC may transmit text messages to that number. These messages may include information relating to an inquiry, updates relevant to a matter initiated by the individual, scheduling communications, or verification requests. Legacy Solutions LLC adheres to the strict requirements governing mobile data. No mobile information will be shared with third parties or affiliates for marketing or promotional purposes. Text messaging originator opt-in data and consent will not be shared with any third parties except for aggregators and providers of the text message services. Mobile information may be shared with subcontractors strictly as necessary to facilitate internal operations and only under confidentiality obligations.</p>
                <p class="text-[16px] text-gray-700">Legacy Solutions LLC may disclose personal information if required by law or compelled by legal process, or if disclosure is reasonably necessary to protect the rights or property of Legacy Solutions LLC, to prevent fraud or illegal activity, or to address the misuse of this landing page. To the extent permitted by law, Legacy Solutions LLC reserves the right to maintain personal information for the period necessary to satisfy legal retention requirements, fulfill business purposes underlying the collection, address disputes, or enforce agreements.</p>
                <p class="text-[16px] text-gray-700">Legacy Solutions LLC employs administrative, technical, and physical safeguards intended to protect information against unauthorized access, alteration, misuse, or disclosure. These safeguards are designed to be reasonable under the circumstances and consistent with practices commonly employed within the industry. Although these measures are intended to reduce the likelihood of unauthorized access, Legacy Solutions LLC does not represent that its systems or transmissions are incapable of penetration or immune from compromise, as no technological system is capable of guaranteeing absolute security.</p>
                <p class="text-[16px] text-gray-700">This landing page is not intended for use by individuals under the age of eighteen. Legacy Solutions LLC does not knowingly collect information from minors. Should information be submitted by a minor, Legacy Solutions LLC will remove the information upon discovery unless retention is required by law.</p>
                <p class="text-[16px] text-gray-700">Individuals may request access to or correction of personal information previously submitted. Individuals may also request deletion of personal information, subject to applicable law and legitimate business needs. Requests must be directed to Legacy Solutions LLC at the address, email, or telephone number provided below.</p>
                <p class="text-[16px] text-gray-700">Legacy Solutions LLC reserves the right to amend this Privacy Policy at any time. Any amended version will be posted to this page with a revised effective date. Continued use of the landing page following a revision constitutes acceptance of the amended policy.</p>
                <p class="text-[16px] text-gray-700">Questions regarding this Privacy Policy may be directed to Legacy Solutions LLC at tcornish@legacysolutionsllc.us, 504-638-9090.</p>
            </div>
        </div>
    </div>
</template>