<template>
    <div class="bg-[#F3F6F9] px-5 md:px-[30px] lg:px-0">
        <div class="container max-w-7xl mx-auto py-7 md:py-[60px]">
            <div class="flex flex-col gap-5">
                <h2 class="font-outfit text-[#00274D] text-3xl md:text-4xl lg:text-5xl md:leading-[46px] font-semibold uppercase leading-tight" style="color: #00274D;">
                    SMS TERMS AND CONDITIONS
                </h2>
                <div class="flex items-center text-[#0f75bc] text-[16px]">
                    <!-- <span> -->
                        <svg aria-hidden="true" class="mr-1" fill="#0f75bc" width="16" height="16" viewBox="0 0 448 512"><path d="M148 288h-40c-6.6 0-12-5.4-12-12v-40c0-6.6 5.4-12 12-12h40c6.6 0 12 5.4 12 12v40c0 6.6-5.4 12-12 12zm108-12v-40c0-6.6-5.4-12-12-12h-40c-6.6 0-12 5.4-12 12v40c0 6.6 5.4 12 12 12h40c6.6 0 12-5.4 12-12zm96 0v-40c0-6.6-5.4-12-12-12h-40c-6.6 0-12 5.4-12 12v40c0 6.6 5.4 12 12 12h40c6.6 0 12-5.4 12-12zm-96 96v-40c0-6.6-5.4-12-12-12h-40c-6.6 0-12 5.4-12 12v40c0 6.6 5.4 12 12 12h40c6.6 0 12-5.4 12-12zm-96 0v-40c0-6.6-5.4-12-12-12h-40c-6.6 0-12 5.4-12 12v40c0 6.6 5.4 12 12 12h40c6.6 0 12-5.4 12-12zm192 0v-40c0-6.6-5.4-12-12-12h-40c-6.6 0-12 5.4-12 12v40c0 6.6 5.4 12 12 12h40c6.6 0 12-5.4 12-12zm96-260v352c0 26.5-21.5 48-48 48H48c-26.5 0-48-21.5-48-48V112c0-26.5 21.5-48 48-48h48V12c0-6.6 5.4-12 12-12h40c6.6 0 12 5.4 12 12v52h128V12c0-6.6 5.4-12 12-12h40c6.6 0 12 5.4 12 12v52h48c26.5 0 48 21.5 48 48zm-48 346V160H48v298c0 3.3 2.7 6 6 6h340c3.3 0 6-2.7 6-6z"></path></svg>
                    <!-- </span> -->
                    <span>
                        Effective as of December 2, 2025
                    </span>
                </div>
                <hr>
                <p class="text-[16px] text-gray-700">These SMS Terms and Conditions apply to all text message communications transmitted by or on behalf of Legacy Solutions LLC. By voluntarily submitting a mobile telephone number, responding to a text message sent by Legacy Solutions LLC, or otherwise participating in any messaging program administered by Legacy Solutions LLC, the individual acknowledges and agrees to the terms set forth in this document. These SMS Terms and Conditions constitute a legally binding agreement between the individual and Legacy Solutions LLC and should be reviewed carefully prior to providing any mobile number or engaging in any messaging interaction.</p>
                <p class="text-[16px] text-gray-700">Legacy Solutions LLC uses text messaging as a means of communicating with individuals who have voluntarily provided a mobile number in connection with an inquiry or potential service. Text messages may include confirmations, updates, informational notices, scheduling communication, identity verification messages, and general correspondence necessary to address the subject of an individual’s request. Text messages are not used for advertising or promotional purposes and are limited in scope to matters arising directly from contact initiated by the individual.</p>
                <p class="text-[16px] text-gray-700">By providing a mobile telephone number to Legacy Solutions LLC, the individual represents and warrants that the number belongs to them, that they have authority to receive messages at that number, and that they consent to the receipt of such messages. Message frequency may vary depending upon the nature and timing of the inquiry and may increase or decrease without notice. The individual acknowledges that standard message and data rates may apply and that such charges are imposed by the individual’s wireless carrier, not by Legacy Solutions LLC. The individual further acknowledges that participation in text messaging is not a condition of receiving services and that all communications offered through text message may also be accessed by telephone or email as an alternative.</p>
                <p class="text-[16px] text-gray-700">Individuals may discontinue receiving text messages at any time by replying STOP to any message sent by Legacy Solutions LLC. Upon receipt of a STOP message, Legacy Solutions LLC will make reasonable efforts to honor the request promptly, subject to system limitations and the period necessary to complete the opt-out process. After an opt-out request has been processed, the individual will no longer receive text messages unless the individual later elects to opt in again through a voluntary submission of a mobile number. For assistance with text messaging, an individual may reply HELP to any message, or may contact Legacy Solutions LLC directly at the contact information provided below.</p>
                <p class="text-[16px] text-gray-700">Legacy Solutions LLC maintains strict policies regarding the confidentiality of mobile information. No mobile information will be shared with third parties or affiliates for marketing or promotional purposes. Text messaging originator opt-in data and consent will not be shared with any third parties except for aggregators and providers of the text message services that support transmission of messages. In operating its messaging program, Legacy Solutions LLC may use subcontractors or service providers for technical support, system maintenance, or customer service, and mobile information may be shared with such subcontractors only to the extent necessary to perform these functions. All subcontractors receiving such information are required to maintain confidentiality and are prohibited from using mobile information for any purpose unrelated to the services they are engaged to provide.</p>
                <p class="text-[16px] text-gray-700">Legacy Solutions LLC does not guarantee the delivery of any text message. Delivery is subject to transmission through third-party carriers, technical constraints, network availability, and other factors outside the control of Legacy Solutions LLC. Individuals acknowledge that wireless carriers are not liable for delayed, misdirected, or undelivered messages, and that Legacy Solutions LLC is not responsible for technical errors, system failures, or service interruptions arising from any carrier or third-party service provider.</p>
                <p class="text-[16px] text-gray-700">Legacy Solutions LLC expressly disclaims all warranties, express or implied, related to the messaging program, including warranties of availability, reliability, timeliness, accuracy, or fitness for a particular purpose. Participation in the messaging program is at the individual’s sole risk. To the fullest extent permitted by law, Legacy Solutions LLC shall not be liable for any damages arising from the use of or inability to use the messaging program, including but not limited to damages arising from delays, technical failures, unauthorized access, interruptions, or errors beyond the control of Legacy Solutions LLC.</p>
                <p class="text-[16px] text-gray-700">These SMS Terms and Conditions are governed by the laws of the State of Louisiana. Any claim, dispute, or legal proceeding arising from or relating to text message communications shall be brought exclusively before a court of competent jurisdiction located in Orleans Parish, Louisiana. If any provision of these SMS Terms and Conditions is found to be unenforceable, the remaining provisions shall continue in full force and effect to the extent permitted by law.</p>
                <p class="text-[16px] text-gray-700">Legacy Solutions LLC reserves the right to modify these SMS Terms and Conditions at any time. Any revised version will be posted with a new effective date. Continued participation in the messaging program following publication of revised terms constitutes acceptance of those terms.</p>
                <p class="text-[16px] text-gray-700">Questions concerning these SMS Terms and Conditions, or requests relating to text messaging, may be directed to Legacy Solutions LLC at tcornish@legacysolutionsllc.us, 504-638-9090.</p>
            </div>
        </div>
    </div>
</template>