<template>
    <div class="bg-[#F3F6F9] px-5 md:px-[30px] lg:px-0">
        <div class="container max-w-7xl mx-auto py-7 md:py-[60px]">
            <div class="flex flex-col gap-5">
                <h2 class="font-outfit text-[#00274D] text-3xl md:text-4xl lg:text-5xl md:leading-[46px] font-semibold uppercase leading-tight" style="color: #00274D;">
                    TERMS OF USE
                </h2>
                <div class="flex items-center text-[#0f75bc] text-[16px]">
                    <!-- <span> -->
                        <svg aria-hidden="true" class="mr-1" fill="#0f75bc" width="16" height="16" viewBox="0 0 448 512"><path d="M148 288h-40c-6.6 0-12-5.4-12-12v-40c0-6.6 5.4-12 12-12h40c6.6 0 12 5.4 12 12v40c0 6.6-5.4 12-12 12zm108-12v-40c0-6.6-5.4-12-12-12h-40c-6.6 0-12 5.4-12 12v40c0 6.6 5.4 12 12 12h40c6.6 0 12-5.4 12-12zm96 0v-40c0-6.6-5.4-12-12-12h-40c-6.6 0-12 5.4-12 12v40c0 6.6 5.4 12 12 12h40c6.6 0 12-5.4 12-12zm-96 96v-40c0-6.6-5.4-12-12-12h-40c-6.6 0-12 5.4-12 12v40c0 6.6 5.4 12 12 12h40c6.6 0 12-5.4 12-12zm-96 0v-40c0-6.6-5.4-12-12-12h-40c-6.6 0-12 5.4-12 12v40c0 6.6 5.4 12 12 12h40c6.6 0 12-5.4 12-12zm192 0v-40c0-6.6-5.4-12-12-12h-40c-6.6 0-12 5.4-12 12v40c0 6.6 5.4 12 12 12h40c6.6 0 12-5.4 12-12zm96-260v352c0 26.5-21.5 48-48 48H48c-26.5 0-48-21.5-48-48V112c0-26.5 21.5-48 48-48h48V12c0-6.6 5.4-12 12-12h40c6.6 0 12 5.4 12 12v52h128V12c0-6.6 5.4-12 12-12h40c6.6 0 12 5.4 12 12v52h48c26.5 0 48 21.5 48 48zm-48 346V160H48v298c0 3.3 2.7 6 6 6h340c3.3 0 6-2.7 6-6z"></path></svg>
                    <!-- </span> -->
                    <span>
                        Effective as of December 2, 2025
                    </span>
                </div>
                <hr>
                <p class="text-[16px] text-gray-700">The following Terms of Use govern access to and use of the landing page maintained by Legacy Solutions LLC, a Louisiana limited liability company. These Terms of Use constitute a binding agreement between the user and Legacy Solutions LLC. By accessing this landing page, submitting information, or engaging in any communication initiated through this landing page, the user acknowledges and affirms that they have read, understood, and agreed to be bound by these Terms of Use.</p>
                <p class="text-[16px] text-gray-700">This landing page is provided solely for the purpose of furnishing general information about the services offered by Legacy Solutions LLC and enabling individuals to request contact or assistance. The information presented is not intended to serve as legal, financial, tax, or other professional advice and should not be relied upon by any person for any purpose other than to understand the nature of the services offered. No attorney-client relationship, agency relationship, fiduciary duty, or other professional relationship is formed simply by viewing the landing page, submitting a form, or contacting Legacy Solutions LLC. Any formal professional relationship between an individual and Legacy Solutions LLC must be established in a separate written agreement duly executed by all necessary parties.</p>
                <p class="text-[16px] text-gray-700">The user agrees to use the landing page only for lawful purposes and in a manner consistent with these Terms of Use. The user may not engage in conduct that could impair the performance, accessibility, reliability, or security of the landing page. Unauthorized attempts to access systems, circumvent security measures, interfere with communications, or modify website content are strictly prohibited.</p>
                <p class="text-[16px] text-gray-700">If a telephone number or mobile number is provided, the user expressly consents to receive communications, including text messages, relating to the user’s inquiry or the services requested. Message frequency may vary. Message and data rates may apply. The user may discontinue text messages at any time by replying STOP. For assistance, the user may reply HELP. Carriers are not responsible for delays or failures in message delivery. No mobile information will be shared with third parties for marketing purposes. Text messaging originator opt-in data and consent will not be shared with any third parties except for aggregators and providers of the text message services.</p>
                <p class="text-[16px] text-gray-700">All content appearing on this landing page is the property of Legacy Solutions LLC or is used with permission. This includes all textual material, design elements, layout, trademarks, service marks, and proprietary information. Unauthorized reproduction, distribution, or modification of any content is strictly prohibited.</p>
                <p class="text-[16px] text-gray-700">Legacy Solutions LLC disclaims all warranties of any kind, whether express or implied, relating to the operation, performance, availability, or accuracy of this landing page. The landing page is provided on an as-is and as-available basis. Legacy Solutions LLC does not guarantee that the landing page will be uninterrupted, error-free, free of defects, or free from security risks. The user assumes all risks associated with the use of this landing page.</p>
                <p class="text-[16px] text-gray-700">To the fullest extent permitted by Louisiana law, Legacy Solutions LLC shall not be liable for any damages arising out of the use of, or inability to use, this landing page or any content contained herein. This limitation applies to claims based in contract, tort, negligence, strict liability, or any other legal theory. Legacy Solutions LLC shall not be responsible for the actions, omissions, or failures of third-party service providers, including but not limited to telecommunications carriers, hosting providers, and messaging platforms.</p>
                <p class="text-[16px] text-gray-700">The user agrees to indemnify, defend, and hold harmless Legacy Solutions LLC from any claims, losses, liabilities, costs, or expenses arising out of the user’s misuse of the landing page or violation of these Terms of Use.</p>
                <p class="text-[16px] text-gray-700">These Terms of Use shall be governed by and construed in accordance with the laws of the State of Louisiana. Any legal action or proceeding shall be brought exclusively in a court of competent jurisdiction located in Orleans Parish, Louisiana.</p>
                <p class="text-[16px] text-gray-700">Legacy Solutions LLC reserves the right to revise these Terms of Use at any time. Continued use of the landing page after publication of amended terms constitutes acceptance of the amended terms.</p>
                <p class="text-[16px] text-gray-700">Questions concerning these Terms of Use may be directed to Legacy Solutions LLC at tcornish@legacysolutionsllc.us, 504-638-9090.</p>
                
            </div>
        </div>
    </div>
</template>