<template>
    <div class="bg-[#F3F6F9] px-5 md:px-[30px] lg:px-0">
        <div class="container max-w-7xl mx-auto py-7 md:py-[60px]">
            <div class="flex flex-col gap-5">
                <h2 class="font-outfit text-[#00274D] text-3xl md:text-4xl lg:text-5xl md:leading-[46px] font-semibold uppercase leading-tight" style="color: #00274D;">
                    WEBSITE DISCLAIMER
                </h2>
                <div class="flex items-center text-[#0f75bc] text-[16px]">
                    <!-- <span> -->
                        <svg aria-hidden="true" class="mr-1" fill="#0f75bc" width="16" height="16" viewBox="0 0 448 512"><path d="M148 288h-40c-6.6 0-12-5.4-12-12v-40c0-6.6 5.4-12 12-12h40c6.6 0 12 5.4 12 12v40c0 6.6-5.4 12-12 12zm108-12v-40c0-6.6-5.4-12-12-12h-40c-6.6 0-12 5.4-12 12v40c0 6.6 5.4 12 12 12h40c6.6 0 12-5.4 12-12zm96 0v-40c0-6.6-5.4-12-12-12h-40c-6.6 0-12 5.4-12 12v40c0 6.6 5.4 12 12 12h40c6.6 0 12-5.4 12-12zm-96 96v-40c0-6.6-5.4-12-12-12h-40c-6.6 0-12 5.4-12 12v40c0 6.6 5.4 12 12 12h40c6.6 0 12-5.4 12-12zm-96 0v-40c0-6.6-5.4-12-12-12h-40c-6.6 0-12 5.4-12 12v40c0 6.6 5.4 12 12 12h40c6.6 0 12-5.4 12-12zm192 0v-40c0-6.6-5.4-12-12-12h-40c-6.6 0-12 5.4-12 12v40c0 6.6 5.4 12 12 12h40c6.6 0 12-5.4 12-12zm96-260v352c0 26.5-21.5 48-48 48H48c-26.5 0-48-21.5-48-48V112c0-26.5 21.5-48 48-48h48V12c0-6.6 5.4-12 12-12h40c6.6 0 12 5.4 12 12v52h128V12c0-6.6 5.4-12 12-12h40c6.6 0 12 5.4 12 12v52h48c26.5 0 48 21.5 48 48zm-48 346V160H48v298c0 3.3 2.7 6 6 6h340c3.3 0 6-2.7 6-6z"></path></svg>
                    <!-- </span> -->
                    <span>
                        Effective as of December 2, 2025
                    </span>
                </div>
                <hr>
                <p class="text-[16px] text-gray-700">This Website Disclaimer sets forth the terms and limitations governing the use of the landing page maintained by Legacy Solutions LLC, a Louisiana limited liability company. The landing page is provided for informational purposes only. By accessing or viewing the content of this landing page, the user acknowledges and agrees to the terms and limitations contained herein. The content of this landing page is not intended to, and does not, constitute legal advice, financial advice, tax advice, professional guidance, or a substitute for consultation with a qualified professional. The information contained on this landing page is general in nature and may not apply to any specific factual or legal circumstance. Individuals are strongly encouraged to consult with a qualified professional before making decisions that may have legal or financial consequences.</p>
                <p class="text-[16px] text-gray-700">The use of this landing page does not create an attorney-client relationship, an agency relationship, a fiduciary relationship, or any contractual or professional relationship between the user and Legacy Solutions LLC. No such relationship shall arise unless and until a separate written agreement is executed by all necessary parties. Communications sent through this landing page, including form submissions or email inquiries, do not create any obligation on the part of Legacy Solutions LLC to represent or provide services to any individual. While Legacy Solutions LLC endeavors to respond to legitimate inquiries, no guarantee is made that all communications will be reviewed or answered.</p>
                <p class="text-[16px] text-gray-700">Legacy Solutions LLC makes reasonable efforts to ensure that the information presented on this landing page is accurate and current; however, Legacy Solutions LLC does not warrant or guarantee the accuracy, completeness, timeliness, or reliability of the content. The information may contain errors, omissions, outdated references, or typographical inaccuracies. Laws, regulations, and procedures may change, and the applicability of such changes may vary depending on the specific facts and circumstances. Legacy Solutions LLC expressly disclaims any duty to update or correct the content of this landing page, and any reliance placed upon the content is done at the sole risk of the user.</p>
                <p class="text-[16px] text-gray-700">The landing page may contain references or links to external websites or third-party resources. These references are provided solely as a convenience and do not constitute an endorsement, approval, recommendation, warranty, or representation concerning any third-party content, product, service, policy, or practice. Legacy Solutions LLC is not responsible for the accuracy, legality, content, or security of any external website or resource and shall not be liable for any damages arising from the use of or reliance on any third-party site. Users access third-party sites at their own risk and should review the terms and privacy policies applicable to such sites.</p>
                <p class="text-[16px] text-gray-700">Legacy Solutions LLC does not guarantee that the landing page will remain available, uninterrupted, or free from defects. Access to the landing page may be suspended or terminated temporarily or permanently without notice. Legacy Solutions LLC does not guarantee that the landing page will be free from viruses, malware, security vulnerabilities, or harmful components. Users are responsible for implementing their own technical safeguards, including antivirus protections and security measures. Legacy Solutions LLC is not responsible for any loss, corruption, unauthorized access, or misuse of data transmitted through the landing page or through related communication channels.</p>
                <p class="text-[16px] text-gray-700">To the fullest extent permitted by Louisiana law, Legacy Solutions LLC disclaims all warranties, express or implied, including warranties of accuracy, completeness, merchantability, fitness for a particular purpose, and non-infringement. The landing page is provided on an as-is and as-available basis. Legacy Solutions LLC shall not be liable for any damages, losses, claims, expenses, or liabilities arising out of or relating to the use of, or reliance on, the landing page or any content contained herein. This limitation applies to all theories of liability, including negligence, tort, contract, strict liability, and any other legal theory, regardless of whether Legacy Solutions LLC has been advised of the possibility of such damages.</p>
                <p class="text-[16px] text-gray-700">Users of this landing page agree to indemnify and hold harmless Legacy Solutions LLC from and against any and all claims, liabilities, damages, losses, or expenses, including but not limited to attorneys’ fees and costs, arising out of or related to the user’s use of the landing page, reliance on its content, violation of this Website Disclaimer, or violation of any applicable law or regulation.</p>
                <p class="text-[16px] text-gray-700">This Website Disclaimer is governed by the laws of the State of Louisiana. Any dispute arising out of or relating to this Website Disclaimer or the use of this landing page shall be brought exclusively in a court of competent jurisdiction located in Orleans Parish, Louisiana. If any provision of this Website Disclaimer is found to be unenforceable, the remaining provisions shall continue in full force and effect to the extent permitted by law.</p>
                <p class="text-[16px] text-gray-700">Legacy Solutions LLC reserves the right to modify this Website Disclaimer at any time without prior notice. Any revised version will be posted on this landing page with an updated effective date. Continued use of the landing page following the posting of a revised disclaimer shall constitute acceptance of the revised terms.</p>
                <p class="text-[16px] text-gray-700">Questions concerning this Website Disclaimer may be directed to Legacy Solutions LLC at tcornish@legacysolutionsllc.us, 504-638-9090.</p>
            </div>
        </div>
    </div>
</template>